name: sqlite
version: 1.0.0
description: >-
  Sqlite3 wrapper. Demo for dart:ffi.
author: Daco Harkes <dacoharkes@google.com>, Samir Jindel <sjindel@google.com>
publish_to: 'none'

environment:
  sdk: ^2.12.0-0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.2.0-nullsafety.1
dev_dependencies:
  test: ^1.5.3
  flutter_test:
    sdk: flutter